export enum DATE_FORMATS {
  DEFAULT_DATE_TIME = "YYYY-MM-DDTHH:mm:ss",
  DEFAULT_DATE = "YYYY-MM-DD",
  DEFAULT_TIME = "HH:mm",
  DATE_PICKER_DATE_TIME = "MMMM d, yyyy - HH:mm",
  DATE_FOR_SLOT = "MMMM DD",
  DATE_FOR_SCHEDULE = "MMMM dd",
}
